### ISSUE TITLE
CovercachePrepopulate stopped working

### ISSUE THREAD

**Issue by GK-774** [jcorporation/mympd-scripts#22]
The current CovercachePrepopulate script throws this error:

Jul 14 20:41:49 mpd9.hal9000.at mympd[58159]: ERROR    scripts_worker  "default": CovercachePrepopulate: Covercache: Unknown filetype
Jul 14 20:41:49 mpd9.hal9000.at mympd[58159]: ERROR    scripts_worker  "default": Error executing script CovercachePrepopulate: Unknown error: [string "..."]:37: bad argument #1 to 'write' (string expected, got FILE*)

An older version (end of June) works normally on the same system.

**Comment by jcorporation** [comment]
Is fixed. I found another problem if ssl is enabled for myMPD. This bug is fixed in the current devel branch of myMPD.

Errors like the following are benign. myMPD delivers the default placeholder images as compressed svg's, but the integrated http client does not support this.

```
20:22:08 WARN     scripts_worker  Could not determine mime type from bytes "3C3F786D6C2076657273696F"
20:22:08 WARN     scripts_worker  No extension found for mime_type "application/octet-stream"
20:22:08 ERROR    scripts_worker  "default": CovercachePrepopulate: Covercache: Unknown filetype
```

**Comment by GK-774** [comment]
Yes, can confirm it works now. Thanks!
