### ISSUE TITLE
Scripting - executing shell command does not work

### ISSUE THREAD

**Issue by td598** [jcorporation/mympd-scripts#25]
myMPD version: 18.0.0

I try to get script "JukeboxBlissify" to work. I installed everything neccessary and when I run the following command that is created in the script in a terminal it works great:
/home/tc/.cargo/bin/blissify -c /home/tc/.config/bliss-rs/config.json playlist --seed-song --dry-run --from-song "/var/lib/mpd/music/A Tasty Sound Collection/Cigars & Sounds/01 His Hometown.flac" 52 2>/dev/null

Running this in the script does not work at all. "mympd.os_capture(cmd)" result is nil.
Mympd message: "Failure adding songs to jukebox queue"
I am aware of issue 399 but it did not work either.

**Server platform (please complete the following information):**
 - Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux

 - MPD version: 0.23.5

**Client platform (please complete the following information):**
 - Device: Laptop
 - OS: Windows 11
 - Browser Firefox
 - Browser version 131.0 (64-Bit)

**Comment by td598** [comment]
This is the output of the journalctl command: Oct 11 09:46:34 Test mympd[6000]: sh: 1: /home/tc/.cargo/bin/blissify: Permission denied
I expected this to be an authorization topic. But to be honest I am not good with this and do not know how to solve.

**Comment by jcorporation** [comment]
Simply move the blissify installation out of your home directory. The default systemd unit of myMPD has ProtectHome set to true and this prevents myMPD accessing home directories.
