### ISSUE TITLE
Radiobrowser - script

### ISSUE THREAD

**Issue by td598** [jcorporation/mympd-scripts#26]
myMPD version: 18.0.0

I try to get the radiobrowser script to work. The "AppendToQueue" selection works just fine. But the "AddToFavorites" does not. I traced the problem back to this call: "rc, result = mympd.api("MYMPD_API_WEBRADIO_FAVORITE_SAVE", data)". The message is: "Fehler beim Ausführen des Skripts Radiobrowser: Unknown error: message is NULL"

Server platform (please complete the following information):

    Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux

    MPD version: 0.23.5

Client platform (please complete the following information):

    Device: Laptop
    OS: Windows 11
    Browser Firefox
    Browser version 131.0 (64-Bit)

**Comment by jcorporation** [comment]
The script uses an old parameters for MYMPD_API_WEBRADIO_FAVORITE_SAVE api. This is now fixed.
