### ISSUE TITLE
Blissify not working in script environment

### ISSUE THREAD

**Issue by td598** [jcorporation/mympd-scripts#28]
I have setup some RPi's running MPD/myMPD in satellite mode connected to a host. This is running fine. I have also running blissify in a script on each of the RPi's. Before I moved to the satellite setup this worked fine as well. Now it only works on command line but not in the script. I guess it has something to do with the MPD_HOST environment variable which seems to be always standard in the script but need to be changed to /run/mpd/socket for blissify to work?

**Comment by jcorporation** [comment]
Please post logs of script execution.

**Comment by td598** [comment]
I found the problem. I just forgot to make the setting persistent. Now it works. Thank you.
