### ISSUE TITLE
get_song_details does not work

### ISSUE THREAD

**Issue by td598** [jcorporation/mympd-scripts#29]
I try to get the lyric scipts to work but getting an error already at the beginning when song details are retrived. I setup a test script:

mympd.init()
local uri_t = mympd_state.current_song.uri
local rc, song = mympd.api("MYMPD_API_SONG_DETAILS", {uri_t})
if rc ~= 0 then
    return mympd.http_jsonrpc_error("MYMPD_API_LYRICS_GET", "Song not found 1")
end

And this is the result:
HTTP/1.1 200 OK
Content-length: 152
Connection: close
Content-Type: application/json

{"id":872398293,"jsonrpc":"2.0","error":{"method":"MYMPD_API_LYRICS_GET","facility":"script","severity":"error","message":"Song not found 1","data":[]}}
Can you help again?

**Comment by jcorporation** [comment]
Which myMPD version?

Attach myMPD debug logs of script execution.

**Comment by td598** [comment]
myMPD version is 18.0.0
This is the log:
 journalctl -fu mympd
Nov 10 09:22:47 Wohnzimmer mympd[808]: NOTICE   mpdworker       "default": Connected to MPD
Nov 10 09:22:47 Wohnzimmer mympd[808]: NOTICE   mpdworker       0 smart playlists updated, 13 already up-to-date
Nov 10 09:22:47 Wohnzimmer mympd[808]: NOTICE   mpdworker       Stopping mpd_worker thread
Nov 10 09:26:17 Wohnzimmer mympd[808]: NOTICE   mympdapi        Starting mpd_worker thread for MYMPD_API_CACHE_DISK_CROP
Nov 10 09:26:17 Wohnzimmer mympd[808]: NOTICE   mpdworker       Deleted 0 files from cover cache
Nov 10 09:26:17 Wohnzimmer mympd[808]: NOTICE   mpdworker       Deleted 0 files from lyrics cache
Nov 10 09:26:17 Wohnzimmer mympd[808]: NOTICE   mpdworker       Deleted 0 files from thumbs cache
Nov 10 09:26:17 Wohnzimmer mympd[808]: NOTICE   mpdworker       Deleted 0 files from misc cache
Nov 10 09:26:17 Wohnzimmer mympd[808]: NOTICE   mpdworker       Stopping mpd_worker thread
Nov 10 10:03:00 Wohnzimmer mympd[808]: ERROR    webserver       54bfd69 1 mongoose.c:1363:mg_error      139 14 socket error

**Comment by jcorporation** [comment]
Always upgrade to latest myMPD version before opening an issue.

Your API Call for to get song details is incorrect. Refer to the api documentation for correct parameters: https://jcorporation.github.io/myMPD/060-references/api/methods/

**Comment by td598** [comment]
it works when I use the imported script.

local uri_t = mympd_state.current_song.uri
rc, song = mympd.api("MYMPD_API_SONG_DETAILS", {uri = uri_t})

 But I do not understand why as I do not  understand this construct {uri = uri_t}.  It only works this way.

**Comment by jcorporation** [comment]
```lua
{ uri = uri_t }
```

This defines a Lua table. Syntax is key = value. In this case the key is "uri" and the value is uri of the song.
